// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdn6lpVPQkx-GsFqcCurd725mcyeFUh-w',
    appId: '1:76964777636:web:00f844312d812b553fa031',
    messagingSenderId: '76964777636',
    projectId: 'vird-fc834',
    authDomain: 'vird-fc834.firebaseapp.com',
    storageBucket: 'vird-fc834.firebasestorage.app',
    measurementId: 'G-37N0KW13HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAErTjZoyQiKUagJH_UZE2X9A1EA4Hchn0',
    appId: '1:76964777636:android:74951407ab9810f33fa031',
    messagingSenderId: '76964777636',
    projectId: 'vird-fc834',
    storageBucket: 'vird-fc834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlxwCVGBfO8RQU6cdzms7pwijuSF7C5A',
    appId: '1:76964777636:ios:f0cef3e6141ea6173fa031',
    messagingSenderId: '76964777636',
    projectId: 'vird-fc834',
    storageBucket: 'vird-fc834.firebasestorage.app',
    iosBundleId: 'com.example.virdApp',
  );

}