// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjIvvBQI2_fXSjTcHwgjzS4Cw-4Z0qZA',
    appId: '1:33941601352:web:d0703d266c79339f6b2c7d',
    messagingSenderId: '33941601352',
    projectId: 'vird-app-52db1',
    authDomain: 'vird-app-52db1.firebaseapp.com',
    storageBucket: 'vird-app-52db1.firebasestorage.app',
    measurementId: 'G-C4MCSE4LN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKftU-WekcTsepLJLICfcdzSEaXfsTYJ0',
    appId: '1:33941601352:android:eddc28e3f867d5976b2c7d',
    messagingSenderId: '33941601352',
    projectId: 'vird-app-52db1',
    storageBucket: 'vird-app-52db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9YoqKVhvrKVxosaoQgvGI-OAa9ENAp9c',
    appId: '1:33941601352:ios:09f9c6778a0d65686b2c7d',
    messagingSenderId: '33941601352',
    projectId: 'vird-app-52db1',
    storageBucket: 'vird-app-52db1.firebasestorage.app',
    iosClientId: '33941601352-766fcv35krto57pr8csdfi4977nmscg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.virdApp',
  );
}
